lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5555/24h-rings-clock-card.js
      type: module

demo:

input_datetime:
  start_time:
    name: Input for start time
    has_date: false
    has_time: true
    initial: '10:30'
  end_time:
    name: Input for end time
    has_date: false
    has_time: true
    initial: '21:11'
  start_time_2:
    name: Input for start time
    has_date: false
    has_time: true
    initial: '01:30'
  end_time_2:
    name: Input for end time
    has_date: false
    has_time: true
    initial: '11:11'
  my_custom_marker_time:
    name: Input for custom event
    has_date: false
    has_time: true
    initial: '14:51'

template:
  - trigger:
      - platform: time_pattern
        seconds: "/1"
    sensor:
      - name: Running hour
        unique_id: running_hour
        state: >
          {% set current_second = now().second % 24 %}
          {{ current_second % 24 }}:00
        attributes:
          datum: >
            {% set current_second = now().second % 24 %}
            {{ current_second % 24 }}:30

  - trigger:
      - platform: time_pattern
        seconds: "/1"
    sensor:
      - name: Running hour (6h Late)
        unique_id: running_hour_6hr_late
        icon: mdi:clock-minus-outline
        state: >
          {% set current_second_mapped = now().second % 24 %}
          {{ (current_second_mapped - 6) % 24 }}:00
        attributes:
          datum: >
            {% set current_second_mapped = now().second % 24 %}
            {{ (current_second_mapped - 6) % 24 }}:30
