name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Faster HACS Action
        uses: TheRealWaldo/faster-hacs-action@v0.0.7"
        with:
          category: integration